version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-hello
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # optional: live code reload if you mount
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data:
